### ISSUE TITLE
Como usuario de conciliación bancaria requiero procesar el pago de una comisión EDENRED

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#110]
### Happy path
1. El tesorero ingresa al sistema de conciliaciones bancarias
2. El tesorero elige una conciliación
3. El tesorero elige la opción **Pagar** del menú contextual
4. El usuario hace clic en el botón pagar
5. El sistema calcula el monto total de pago
6. El sistema registra el total del pago
7. El sistema informa de la finalización del proceso

## Prototipo
![image](https://user-images.githubusercontent.com/30910881/40998357-2c67da44-68cd-11e8-8446-371760440deb.png)

## Implementación
- Modificar la pantalla **AplicarPago.aspx** y **AplicarPago.aspx.cs**
- Modificar el método **btnAplicarPagos_Click**
- Identificar y analizar el método **MovimientoCaja.Guardar**  
- Modificar el método **MovimientoCaja.MovimientoCajaAlta** para que calcular el total es igual a la suma del monto del Depósito en el Estado de Cuenta MÁS la Comisión capturada por el cliente.
- Modificar el método **MovimientoCaja. AplicarCobros**  para que calcular el total es igual a la suma del monto del Depósito en el Estado de Cuenta MÁS la Comisión capturada por el cliente.

**Comment by Ruben-1** [comment]
Los ajustes se harán directamente en los SPs que calculan los valores:
- spCBConsultaMovimientoCajaAlta
- spCBActualizaConciliacionPedido
