### ISSUE TITLE
Selección de archivo aparece en una nueva columna

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#18]
La pantalla de importación de archivos externos presenta una diferencia respecto a la versión inicial
"Entrar al Menú princial e ir a la opción ""Archivos"" -> ""Importar"".
La interfaz de usuario se presenta de un modo diferente al de la versión original: 
-El control de selección de archivos se muestra a la derecha (nueva columna)
-Se deberá ver bajo el textbox ""Año"" y arriba de los botones ""Cancelar y Guardar"""

**Comment by Ruben-1** [comment]
No parece error, está programado para que se vean dos columnas
