### ISSUE TITLE
Etiquetas Cliente y factura

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#20]

**Comment by Ruben-1** [comment]
Comentario

**Comment by ivantrujillo79** [comment]
El ajuste aplica a las pantallas de conciliación 
-Cantidad concuerda
-Cantidad y referencia concuerda
-Uno a varios

**Comment by Ruben-1** [comment]
Reemplazar por "cliente" y "factura"
