### ISSUE TITLE
Modificar etiquetas PedidoReferencia por Documento

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#21]

**Comment by ivantrujillo79** [comment]
Aplica a los formularios de:

-Cantidad concuerda
-Cantidad y referencia concuerdan
-Manual
-Pagos

**Comment by Ruben-1** [comment]
checar tipo conciliacion 2 o 6
Marzo 2014

**Comment by Ruben-1** [comment]
No se encuentra "PedidoReferencia" en UnoAVarios ni Manual.
Se reemplaza "Referencia" por "Documento" en estas páginas.

**Comment by ivantrujillo79** [comment]
Escenario usado para reproducir la prueba 

Tipo conciliacion: 2
Status: Abierta
Año: 2014
Mes: Marzo
