### ISSUE TITLE
Al dar clic en la Forma Conciliación Uno a Varios aparece una  Excepción.. Object Reference not set a object

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#24]
Al dar clic en la Forma Conciliación Uno a Varios aparece una  Excepción.. Object Reference not set a object

**Comment by Ruben-1** [comment]
Se puede replicar la incidencia en Cantidad y referencia concuerdan,
pero no en Uno a varios.

**Comment by ivantrujillo79** [comment]
Escenario usado para reproducir el caso:

Tipo conciliacion: 2
Status: Abierta
Año: 2014
Mes: Marzo
