### ISSUE TITLE
Web User Control Listado de Cajas

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#37]

**Comment by ivantrujillo79** [comment]
1. Crear la estructura Caja con dos atributos: ID y Descripción
2. Crear el web user control llamado WUCListadoCajas consistente en:
     a) Una propiedad Cajas del tipo List<Caja>
     b) Una propiedad CajasSeleccionadas del tipo List<Caja> con las instancias de las cajas seleccionadas por el usuario
     a) Un panel fijo con altura de 250 pixeles
     b) Un checkbox "Todos" que seleccione o des seleccione todos los elementos de la lista
     c) Un checkbox para cada elemento de la propiedad Cajas

**Comment by Ruben-1** [comment]
Rama: RM_Feature_Wuc_ListadoCajas_08_03_2018
