### ISSUE TITLE
Resolución del Defecto ID 80

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#50]
UnoAVariosPedidos	

El botón de  PedidoREferencia en la búsqueda de pedidos, si me esta devolviendo registros, pero al momento de conciliarlos no esta realizando la acción correcta, la acción correcta debe de ser el mismo comportamiento que la búsqueda por cliente.

![image.png](https://images.zenhubusercontent.com/59a050988f62dc7798c4133f/6338f1a4-ce1b-404b-8047-cebdd415b07f)

![image.png](https://images.zenhubusercontent.com/59a050988f62dc7798c4133f/39b2db58-8a61-4059-b89d-7a20b3c03f2a)

![image.png](https://images.zenhubusercontent.com/59a050988f62dc7798c4133f/77eb2586-f3d7-4cae-937d-789c4165d88d)

**Comment by Ruben-1** [comment]
El incidente lo atiende Ricardo bajo la rama: RRV_Bugfix_DefectoID80
