### ISSUE TITLE
Bug - Validación PedidoRefrencia para la carga de archivos Excel

### ISSUE THREAD

**Issue by ivantrujillo79** [ivantrujillo79/conciliacionbancaria#6]
-La validación del PedidoRefrencia para la carga de archivos Excel no se está realizando
-El número de cuenta a validar no se estaba asignando a la propiedad correspondiente del componente de carga de Excel
-Defecto cosmético válido en vez de valido

**Comment by rrojastransformait** [comment]
Se hicieron las correcciones
